FROM docker.io/library/ros@sha256:1813d3c85d7f96ff7d3012d865204583255740182db5d0065f8f8cd029a83138
RUN apt-get update && apt-get install -y --no-install-recommends python3-numpy python3-matplotlib \
    && rm -rf /var/lib/apt/lists/*
